### ISSUE TITLE
thresholdMatDensity missing in Toolbox

### ISSUE THREAD

**Issue by MirjamQuaak** [asizemore/Dynamic-Graph-Metrics#2]
Dear Ms. Sizemore,
According to the readme, the function thresholdMatDensity should be in this toolbox, but I believe this is missing. As I am trying to run broadcastRecievecentrality, it would be great if this function could also be uploaded! Thanks in advance!

**Comment by asizemore** [comment]
Thank you so much for the feedback! This function has been uploaded. Please
feel free to reach out if you have any more questions or if you run into
any trouble!

Best,
Ann Sizemore
