### ISSUE TITLE
Temporal community structure

### ISSUE THREAD

**Issue by sunqiqi123** [asizemore/Dynamic-Graph-Metrics#4]
I'm glad your code is open to the public. But for "Temporal community structure" I didn't find this part of the code.

**Comment by asizemore** [comment]
Hi @sunqiqi123 ,

Temporal community structure isn't implemented in this repository. In the paper we only illustrated the idea. I would look to the references in that section of the paper or a tool such as the Brain Connectivity Toolbox for an implementation.

Additionally, please note this repository is no longer maintained. Please let me know if you have any questions.

Thanks!
